version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
  dashboard:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: streamlit run src/dashboard/app.py --server.port 8501 --server.address 0.0.0.0
